BUNDLE_NAME = VePreferences
VePreferences_FILES = $(wildcard Controllers/*.m Cells/*.m)
VePreferences_FRAMEWORKS = UIKit
VePreferences_PRIVATE_FRAMEWORKS = Preferences
VePreferences_INSTALL_PATH = /Library/PreferenceBundles
VePreferences_CFLAGS = -fobjc-arc

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
