TWEAK_NAME = VeCore
VeCore_FILES = VeCore.m $(wildcard ../../Manager/*.m ../../Utils/*.m)
VeCore_CFLAGS = -fobjc-arc
VeCore_FRAMEWORKS = UIKit

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
